const hardcodedUsers = [
{
        name: 'Saheed',
        handle: 'Saheed22',
        email: 'omoceleb222@gmail.com',
        phone: '+2348065837534',
        country: 'NG',
        accessCode: '1736SSS',
        unlockedVideos: [],
        suspended: 'F',
        subscription: 'T',
        subscriptionExpiry: new Date(new Date().setMonth(new Date().getMonth() + 1)).toISOString(),
        availableBalance: 0.00,
        referralBalance: 0.00,
        avatar: 'https://via.placeholder.com/150/007bff/FFFFFF?text=JC'
    },
        {
        name: 'Jarota',
        handle: 'heyhey',
        email: 'jarota303@gmail.com',
        phone: '+2348167977962',
        country: 'NG', 
        accessCode: '3033OZI',
        unlockedVideos: [],
        suspended: 'F', 
        subscription: 'T', 
        subscriptionExpiry: new Date(new Date().setMonth(new Date().getMonth() + 1)).toISOString(), 
        availableBalance: 0.00,
        referralBalance: 0.00,
        avatar: 'https://via.placeholder.com/150/007bff/FFFFFF?text=AA'
    },
        {
        name: 'Team(Joint Acc)',
        handle: 'paulvick',
        email: 'paulvick@milaaje.org',
        phone: '+234123456789',
        country: 'NG', 
        accessCode: '4321PAV',
        unlockedVideos: [],
        suspended: 'F', 
        subscription: 'T', 
        subscriptionExpiry: new Date(new Date().setMonth(new Date().getMonth() + 1)).toISOString(), 
        availableBalance: 4500.00,
        referralBalance: 0.00,
        avatar: 'https://via.placeholder.com/150/007bff/FFFFFF?text=AA'
    },
        {
        name: 'Abdallah Afaridjan',
        handle: 'Abdallah',
        email: 'abdallahafaridjan@gmail.com',
        phone: '0242023867',
        country: 'GH', 
        accessCode: '3487ABD',
        unlockedVideos: [],
        suspended: 'F', 
        subscription: 'F', 
        subscriptionExpiry: new Date(new Date().setMonth(new Date().getMonth() - 1)).toISOString(), 
        availableBalance: 0.00,
        referralBalance: 0.00,
        avatar: 'https://via.placeholder.com/150/007bff/FFFFFF?text=AA'
    },
    {
        name: 'Marvin Hush',
        handle: 'Marvin',
        email: 'marvinhush@yahoo.com',
        phone: '+2348160791600',
        country: 'NG',
        accessCode: '1983ABC',
        unlockedVideos: [],
        suspended: 'F',
        subscription: 'F',
        subscriptionExpiry: new Date(new Date().setMonth(new Date().getMonth() - 1)).toISOString(),
        availableBalance: 0.00,
        referralBalance: 0.00,
        avatar: 'https://via.placeholder.com/150/007bff/FFFFFF?text=MH'
    },
    {
        name: 'Sam Esom',
        handle: 'Sam',
        email: 'orjisamuel19@gmail.com',
        phone: '+2347067411418',
        country: 'NG',
        accessCode: '2559SOM',
        unlockedVideos: [],
        suspended: 'F',
        subscription: 'F',
        subscriptionExpiry: new Date(new Date().setMonth(new Date().getMonth() - 1)).toISOString(),
        availableBalance: 0.00,
        referralBalance: 0.00,
        avatar: 'https://via.placeholder.com/150/007bff/FFFFFF?text=SE'
    },
    {
        name: 'Chinetu Emmanuel',
        handle: 'Chinetu',
        email: 'chinetuemmanuel@gmail.com',
        phone: '+2349071375250',
        country: 'NG',
        accessCode: '1058CHI',
        unlockedVideos: [],
        suspended: 'F',
        subscription: 'F',
        subscriptionExpiry: new Date(new Date().setMonth(new Date().getMonth() - 1)).toISOString(),
        availableBalance: 0.00,
        referralBalance: 0.00,
        avatar: 'https://via.placeholder.com/150/007bff/FFFFFF?text=CE'
    },
    {
        name: 'Micah Samuel',
        handle: 'Micah',
        email: 'micahblaq1@gmail.com',
        phone: '+31652560594',
        country: 'NL',
        accessCode: '5442BLA',
        unlockedVideos: [],
        suspended: 'F',
        subscription: 'F',
        subscriptionExpiry: new Date(new Date().setMonth(new Date().getMonth() - 1)).toISOString(),
        availableBalance: 0.00,
        referralBalance: 0.00,
        avatar: 'https://via.placeholder.com/150/007bff/FFFFFF?text=MS'
    },
    {
        name: 'Barnabas Chidindu',
        handle: 'Barnabas',
        email: 'chidindubarnabasiwuafor@gmail.com',
        phone: '+2348066448413',
        country: 'NG',
        accessCode: '1234BAN',
        unlockedVideos: [],
        suspended: 'F',
        subscription: 'F',
        subscriptionExpiry: new Date(new Date().setMonth(new Date().getMonth() - 1)).toISOString(),
        availableBalance: 0.00,
        referralBalance: 0.00,
        avatar: 'https://via.placeholder.com/150/007bff/FFFFFF?text=BC'
    },
    {
        name: 'Emsley Izunna',
        handle: 'Emsley',
        email: 'emsleyizunna@gmail.com',
        phone: '+2348081848198',
        country: 'NG',
        accessCode: '1234IZU',
        unlockedVideos: [],
        suspended: 'F',
        subscription: 'F',
        subscriptionExpiry: new Date(new Date().setMonth(new Date().getMonth() - 1)).toISOString(),
        availableBalance: 0.00,
        referralBalance: 0.00,
        avatar: 'https://via.placeholder.com/150/007bff/FFFFFF?text=EI'
    },
    {
        name: 'Ezumaibe Kelechiukwu',
        handle: 'Ezumaibe',
        email: 'sunshineworldcomputers@yahoo.com',
        phone: '+2349079244440',
        country: 'NG',
        accessCode: '2025ABC',
        unlockedVideos: [],
        suspended: 'F',
        subscription: 'F',
        subscriptionExpiry: new Date(new Date().setMonth(new Date().getMonth() - 1)).toISOString(),
        availableBalance: 0.00,
        referralBalance: 0.00,
        avatar: 'https://via.placeholder.com/150/007bff/FFFFFF?text=EK'
    },
    {
        name: 'Peter obiakonwa',
        handle: 'Peter',
        email: 'peterobiakonwa@gmail.com',
        phone: '+2347048711326',
        country: 'NG',
        accessCode: '2001SHE',
        unlockedVideos: [],
        suspended: 'F',
        subscription: 'F',
        subscriptionExpiry: new Date(new Date().setMonth(new Date().getMonth() - 1)).toISOString(),
        availableBalance: 0.00,
        referralBalance: 0.00,
        avatar: 'https://via.placeholder.com/150/007bff/FFFFFF?text=PO'
    },
    {
        name: 'Agalee Ifeanyi',
        handle: 'Agalee',
        email: 'agaleeifeanyi@gmail.com',
        phone: '+2349057014199',
        country: 'NG',
        accessCode: '5555OKA',
        unlockedVideos: [],
        suspended: 'F',
        subscription: 'F',
        subscriptionExpiry: new Date(new Date().setMonth(new Date().getMonth() - 1)).toISOString(),
        availableBalance: 0.00,
        referralBalance: 0.00,
        avatar: 'https://via.placeholder.com/150/007bff/FFFFFF?text=AI'
    },
    {
        name: 'Denrele Philips',
        handle: 'Denrele',
        email: 'dphilips1122@gmail.com',
        phone: '+2349076621945',
        country: 'NG',
        accessCode: '1414ABC',
        unlockedVideos: [],
        suspended: 'F',
        subscription: 'F',
        subscriptionExpiry: new Date(new Date().setMonth(new Date().getMonth() - 1)).toISOString(),
        availableBalance: 0.00,
        referralBalance: 0.00,
        avatar: 'https://via.placeholder.com/150/007bff/FFFFFF?text=DP'
    },
    {
        name: 'Franklin Afola',
        handle: 'Franklin',
        email: 'pe6970172@gmail.com',
        phone: '+2349038116390',
        country: 'NG',
        accessCode: '1997FRA',
        unlockedVideos: [],
        suspended: 'F',
        subscription: 'F',
        subscriptionExpiry: new Date(new Date().setMonth(new Date().getMonth() - 1)).toISOString(),
        availableBalance: 0.00,
        referralBalance: 0.00,
        avatar: 'https://via.placeholder.com/150/007bff/FFFFFF?text=FA'
    },
    {
        name: 'Chidinma Iheanachor',
        handle: 'Chidinma',
        email: 'lightsolomon210eli@gmail.com',
        phone: '+2348128678246',
        country: 'NG',
        accessCode: '6754IKE',
        unlockedVideos: [],
        suspended: 'F',
        subscription: 'F',
        subscriptionExpiry: new Date(new Date().setMonth(new Date().getMonth() - 1)).toISOString(),
        availableBalance: 0.00,
        referralBalance: 0.00,
        avatar: 'https://via.placeholder.com/150/007bff/FFFFFF?text=CI'
    },
    {
        name: 'Onyeka Arimonu',
        handle: 'Onyeka',
        email: 'omegachris@gmail.com',
        phone: '+23481342..725',
        country: 'NG',
        accessCode: '1345ADC',
        unlockedVideos: [],
        suspended: 'F',
        subscription: 'F',
        subscriptionExpiry: new Date(new Date().setMonth(new Date().getMonth() - 1)).toISOString(),
        availableBalance: 0.00,
        referralBalance: 0.00,
        avatar: 'https://via.placeholder.com/150/007bff/FFFFFF?text=OA'
    },
    {
        name: 'Osmond Echezona',
        handle: 'Osmond',
        email: 'echezonaosmond@gmail.com',
        phone: '+2348061452349',
        country: 'NG',
        accessCode: '5602ECH',
        unlockedVideos: [],
        suspended: 'F',
        subscription: 'F',
        subscriptionExpiry: new Date(new Date().setMonth(new Date().getMonth() - 1)).toISOString(),
        availableBalance: 0.00,
        referralBalance: 0.00,
        avatar: 'https://via.placeholder.com/150/007bff/FFFFFF?text=OE'
    },
    {
        name: 'Modestus Chukwudalu',
        handle: 'Modestus',
        email: 'echezonaosmond@gmail.com',
        phone: '+2348061452349',
        country: 'NG',
        accessCode: '2349ECH',
        unlockedVideos: [],
        suspended: 'F',
        subscription: 'F',
        subscriptionExpiry: new Date(new Date().setMonth(new Date().getMonth() - 1)).toISOString(),
        availableBalance: 0.00,
        referralBalance: 0.00,
        avatar: 'https://via.placeholder.com/150/007bff/FFFFFF?text=MC'
    },
    {
        name: 'Emmanuel Edet',
        handle: 'Emmanuel',
        email: 'okoney12@gmail.com',
        phone: '+2348121272626',
        country: 'NG',
        accessCode: '1234OKO',
        unlockedVideos: [],
        suspended: 'F',
        subscription: 'F',
        subscriptionExpiry: new Date(new Date().setMonth(new Date().getMonth() - 1)).toISOString(),
        availableBalance: 0.00,
        referralBalance: 0.00,
        avatar: 'https://via.placeholder.com/150/007bff/FFFFFF?text=EE'
    },
    {
        name: 'Ethan Customer',
        handle: 'Ethan',
        email: 'benart170708@gmail.com',
        phone: '0539050781',
        country: 'GH',
        accessCode: '2704BEN',
        unlockedVideos: [],
        suspended: 'F',
        subscription: 'F',
        subscriptionExpiry: new Date(new Date().setMonth(new Date().getMonth() - 1)).toISOString(),
        availableBalance: 0.00,
        referralBalance: 0.00,
        avatar: 'https://via.placeholder.com/150/007bff/FFFFFF?text=EC'
    },
    {
        name: 'Happiness Customer',
        handle: 'Happiness',
        email: 'gentility@gmail.com',
        phone: '0538611957',
        country: 'GH',
        accessCode: '1706GER',
        unlockedVideos: [],
        suspended: 'F',
        subscription: 'F',
        subscriptionExpiry: new Date(new Date().setMonth(new Date().getMonth() - 1)).toISOString(),
        availableBalance: 0.00,
        referralBalance: 0.00,
        avatar: 'https://via.placeholder.com/150/007bff/FFFFFF?text=HC'
    },
    {
        name: 'Ahi rig',
        handle: 'Ahi',
        email: 'michelgogo25@gmail.com',
        phone: '0797029097',
        country: 'CI',
        accessCode: '1234AIG',
        unlockedVideos: [],
        suspended: 'F',
        subscription: 'F',
        subscriptionExpiry: new Date(new Date().setMonth(new Date().getMonth() - 1)).toISOString(),
        availableBalance: 0.00,
        referralBalance: 0.00,
        avatar: 'https://via.placeholder.com/150/007bff/FFFFFF?text=AR'
    },
   {
        name: 'Joseph chibuike',
        handle: 'Joseph',
        email: 'josephchibuikeuzoekwelu@gmail.com',
        phone: '08125305570',
        country: 'NG',
        accessCode: '4831KEN',
        unlockedVideos: [],
        suspended: 'F',
        subscription: 'F',
        subscriptionExpiry: new Date(new Date().setMonth(new Date().getMonth() - 1)).toISOString(),
        availableBalance: 0.00,
        referralBalance: 0.00,
        avatar: 'https://via.placeholder.com/150/007bff/FFFFFF?text=JC'
    },
{
        name: 'Ice Consort',
        handle: 'consort',
        email: 'iceconsort@gmail.com ',
        phone: '08027350284',
        country: 'NG',
        accessCode: '2004MAR',
        unlockedVideos: [],
        suspended: 'F',
        subscription: 'T',
        subscriptionExpiry: new Date(new Date().setMonth(new Date().getMonth() + 1)).toISOString(),
        availableBalance: 394000.00,
        referralBalance: 31000.00,
        avatar: 'https://www.dl.dropboxusercontent.com/scl/fi/kyosw1stu56fjin95f7t6/AddText_07-28-12.57.28.jpg?rlkey=7ifjfz1eubskvwr3bajq17shn&st=rz8zy7ol'
    }
];
simulatedUserDatabase = [...hardcodedUsers];
